resources:
  containers:
  - container: mlops
    image: andysong199086/news_clf:3.0

pr: none
trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: devops-vg
  - template: env_template.yml

stages:
  - stage: 'Model_cd'
    displayName: 'Model CD'
    variables: 
      BUILD_ID: $(BUILD.BUILDID)
      BUILD_URL: $(SYSTEM.COLLECTIONURI)$(SYSTEM.TEAMPROJECT)/_build/results?buildId=$(BUILD.BUILDID)
    jobs:
    - job: 'deployment'
      displayName: 'deployment cd'
      container: mlops
      timeoutInMinutes: 0
      steps:
       - task: AzureCLI@1
         displayName: 'deploy aks service'
         inputs:
           azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
           scriptLocation: inlineScript
           workingDirectory: $(Build.SourcesDirectory)
           inlineScript: |
             set -e
             export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
             python deployment/deploy.py
    - job: 'aks_test'
      displayName: 'aks test'
      container: mlops
      timeoutInMinutes: 0
      dependsOn: 'deployment'
      condition: succeeded()
      steps:
      - task: AzureCLI@1
        displayName: 'testing deployed aks'
        inputs:
          azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
          scriptLocation: inlineScript
          workingDirectory: $(Build.SourcesDirectory)
          inlineScript: |
            set -e
            export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
            python deployment/aci_test.py
