resources:
  containers:
  - container: mlops
    image: andysong199086/news_clf:1.0

pr: none
trigger:
  branches:
    include:
    - main

variables:
  - template: env_template.yml
  - group: devops-vg

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Model_CI'
  displayName: 'Model CI'
  jobs:
  - job: 'create_corpus'
    displayName: 'Creating Corpus'
    container: mlops
    timeoutInMinutes: 0
    steps:
    - task: AzurePowerShell@1
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
#        scriptLocation: inlineScript
#        workingDirectory: $(Build.SourcesDirectory)
        scriptType: inlineScript
        azurePowerShellVersion: latestVersion
        inlineScript: |
          set -e
          bash create_corpus.sh
          python py/preprocessing.py --corpus corpus.txt > corpus_clean.txt
          bash split.sh